###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- name: Delete z/OS certificate via TSO commands.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    owner_id: "{{ owner_id_survey | default('IBMUSER') }}"
    cert_type: "{{ cert_type_survey | default('USER') }}"
    cert_label: "{{ cert_label_survey | default('TEST USER') }}"
    check_name: 'IBMRACF,RACF_CERTIFICATE_EXPIRATION'

  tasks:
    - name: Check if certificate is already absent and delete it only if it isn't.
      block:
        - name: Check if cert to be deleted is already absent.
          ibm.ibm_zos_core.zos_tso_command:
            commands: "{{ _commands_ }}"
          register: check_cert
          failed_when: check_cert.output[0].type_name == ""

        - name: delete the cert
          ibm.ibm_zos_core.zos_tso_command:
            commands: "{{ _commands_ }}"
          register: delete_cert
    
    - name: Run Health Checker.
      ibm.ibm_zos_core.zos_tso_command:
        commands: "{{ _commands_ }}"
    


        